### ISSUE TITLE
About the previous question

### ISSUE THREAD

**Issue by Jerry-zzw** [DengPingFan/D3NetBenchmark#10]
Dear Dr.Fan 
The website is very cool!

But, sorry that I didn't make it clear. Let me ask again.

I'm running my own dataset on D3Net and I need those 4 metrics to evaluate the result of the test. However, the output result only contain MAE and f_max(I don't know what is this). 

the output in the log.txt looks like this:

Training :
Loss: 0.154
Validation :
Validation [test]
Loss: 0.156
[test]-> mae:0.0116 f_max:0.1820
Metric_Select[MAE]: 0.0116 (0.0116)
-------------------------------------------------------------------------------
End time :  2021-09-03 04:46:37

Where can I check F-measure, S-measure and E-measure?

Many thanks.

**Comment by DengPingFan** [comment]
Hi, 

It is the max F-measure. 

For other metrics, you can follow these codes such as https://github.com/zzhanghub/eval-co-sod,  https://github.com/plemeri/UACANet, and https://github.com/mczhuge/SOCToolbox/blob/main/codes/metrics.py.  

Thanks.
