### ISSUE TITLE
evaluation tools

### ISSUE THREAD

**Issue by clelouch** [DengPingFan/D3NetBenchmark#11]
Thanks for your code. 
I am confused when i use the provided evaluation tools. I have tried to use other scripts including [evaluation tools in F3Net](https://github.com/weijun88/F3Net) and [evaluation tools in GCPANet](https://github.com/JosephChenHub/GCPANet/tree/master/eval_code). However, the evaluation results are quite different. Could you please tell me the reason?

**Comment by DengPingFan** [comment]
Hi, 

Please check whether they use the adaptive threshold to obtain the results. There are also some standard evaluation toolboxes such as https://github.com/mczhuge/SOCToolbox and https://github.com/DengPingFan/Polyp-PVT. 

Please double-check. 

Best,
