### ISSUE TITLE
http://dpfan.net/d3netbenchmark/   这个网站怎么使用

### ISSUE THREAD

**Issue by Cherich-GL** [DengPingFan/D3NetBenchmark#13]
您好，我打开您的推荐的http://dpfan.net/d3netbenchmark/这个网站，我不知道该怎么使用，
![image](https://user-images.githubusercontent.com/95956260/171808434-84f24e58-f356-4690-97c7-6f9a3c7d44aa.png)
点每个地方都是unable，希望您有时间可以帮我解答一下。非常感谢！！！

**Comment by Cherich-GL** [comment]
您好，我继续这个评估结果，你方便解答一下吗，非常感谢

**Comment by DengPingFan** [comment]
你好，
你加我微信ilovePing-G

祝好

**Comment by DengPingFan** [comment]
您好，那个旧的网页失效了，现在都重新迁移过来了
