### ISSUE TITLE
Some questions about data

### ISSUE THREAD

**Issue by weiliuxm** [DengPingFan/D3NetBenchmark#3]
Hi Dr. Deng,
Thank you for sharing the project.
I would like to train and test with the code on the 5 datasets in figure 10.
I have two main questions as follows.
(1) Are there lists for training data and testing data?
(2) Is the depth channel normalized like  R, G and B channels?
Thank you in advance.

Wei Liu

**Comment by DengPingFan** [comment]
Hi, Wei Liu,

1. Training and testing sets are available on our website: http://dpfan.net/D3NetBenchmark.
2. Depth channel only normalize into [0,1]. 

Best,
