### ISSUE TITLE
Where can I check the evaluate metric?

### ISSUE THREAD

**Issue by Jerry-zzw** [DengPingFan/D3NetBenchmark#9]
Dear Dr.Deng

You have mentioned 4 evaluate metrics in the paper, however, there are only MAE and f_max(I not sure if this is the F-measure) in the result(log.txt). Where can I check all the metrics?

Many thanks

**Comment by DengPingFan** [comment]
Hi, 
Please check our website (http://dpfan.net/d3netbenchmark/), the four metrics are S-measure, E-measure, F-measure, and MAE.

best,
